range_Dxy : [6,18]
range_M : [1.2e14,1e16]
range_z : [0.2, 0.6]
n_bcc_halo_files : 15
filename_halos : 'halos_bcc.fits'
filename_pairs : 'pairs_bcc.fits'
filename_shears : 'shears_bcc_g.fits'
boundary_mpc : 4
create_ellip : False
shear_type : stacked # single, stacked, minimal
Sigma_crit_unit :  kg/m^2 # kg/m^2 or Msol*h/pc^2
save_pairs_plots: False
pixel_size_mpc : 0.25
pair_first : 0
pair_last : 3000


n_samples : 100
n_walkers : 10
n_grid : 100
save_plots : False
kappa0 : { box: { min : 0.    , max : 1  }}
radius : { box: { min : 0.001 , max : 10 }}
h1M200 : { box: { min : 13    , max : 16 }}
h1M200 : { box: { min : 13    , max : 16 }}
filename_pairs :  /scratch/scratch/ucabtok/140324_filaments_fit/140324-run-bcc/pairs_bcc.fits
filename_shears : /scratch/scratch/ucabtok/140324_filaments_fit/140324-run-bcc/shears_bcc_g.fits
filename_pz : /scratch/scratch/ucabtok/140324_filaments_fit/140324-run-bcc/aardvarkv1.0_des_lenscat_s2n10.351.fit
optimization_mode : mcmc