mode : pairs # null1_unpaired or pairs or selftest

# selection of pairs - parameters
range_Dxy : [6,18]
range_M : [1.2e14,1e16]
range_z : [0.2, 0.6]
filename_halos : halos_bcc.fits
filename_pairs : pairs_bcc.fits
filename_pairs_exclude : none # not important when mode==pairs
filename_shears : shears_bcc_g.fits

# dataset specific options
cfhtlens_select_fun : select_halos # available: select_halos , select_halos_LRG , select_halos_LRGCLASS , select_halos_CLUSTERZ
n_bcc_halo_files : 2 # this is only used for bcc
filename_pz : aardvarkv1.0_des_lenscat_s2n10.351.fit
shear1_col : 's1'
shear2_col : 's2'

# properties of ther postage stamp grid
boundary_mpc : 4
shear_type : stacked # single, stacked, minimal
Sigma_crit_unit :  kg/m^2 # kg/m^2 or Msol*h/pc^2
pixel_size_mpc : 0.25 # this is only used when shear_type=stacked
sigma_method : orig # add or orig
sigma_add : 0.001  # this is only used when sigma_method=add

# param boxes
kappa0 : { box: { min : 0       , max : 0.25} , n_grid : 2 }
radius : { box: { min : 0.25    , max : 4  } , n_grid : 2 }
h1M200 : { box: { min : 13      , max : 16 } , n_grid : 30 }
h2M200 : { box: { min : 13      , max : 16 } , n_grid : 30 }

# optimization properties
optimization_mode : mcmc # or gridsearch
# those options are only used when optimization_mode=mcmc
n_samples : 50
n_walkers : 10
n_grid : 100
n_grid_2D : 1000
n_grid_2D : 600

# plotting
save_dist_plots: True
save_model_plots: False
save_pairs_plots: True

# these are currently not used
get_marginals_for_params: [0,1]
get_confidence_intervals: False # true or false, true is untested -- requires get_marginals_for_params=[0,1,2,3]