mode : pairs # null1_unpaired or pairs

range_Dxy : [6,18]
range_M : [1.2e14,1e16]
range_z : [0.2, 0.6]
n_bcc_halo_files : 2
filename_halos : halos_bcc.fits
filename_pairs : pairs_bcc.fits
filename_pairs_exclude : none # not important when mode==pairs
filename_shears : shears_bcc_g.fits
filename_pz : aardvarkv1.0_des_lenscat_s2n10.351.fit
shear1_col : 's1'
shear2_col : 's2'

boundary_mpc : 4
shear_type : stacked # single, stacked, minimal
Sigma_crit_unit :  kg/m^2 # kg/m^2 or Msol*h/pc^2
save_pairs_plots: True
pixel_size_mpc : 0.25
pair_first : 0
pair_last : 10


n_samples : 50
n_walkers : 10
n_grid : 100
kappa0 : { box: { min : 0.    , max : 1  }}
radius : { box: { min : 0.001 , max : 10 }}
h1M200 : { box: { min : 13    , max : 16 }}
h1M200 : { box: { min : 13    , max : 16 }}
optimization_mode : mcmc
sigma_add : 0.001
sigma_method : orig # add or orig
save_plots: False
